# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z-sCZPa-OnYzRt8mdztn9187DSnlbwns
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('drive/MyDrive/scores.csv')



df.head()

df.describe()

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
lm = LinearRegression()



X = np.array(df['After_School_Supper_ADP']).reshape(-1, 1)
y = np.array(df['Average District Score (SAT Math)']).reshape(-1, 1)
lm.fit(X, y)

plt.scatter(df['After_School_Supper_ADP'], df['Average District Score (SAT Math)'])
plt.plot(X, lm.predict(X))
plt.xlabel('After School Supper ADP')
plt.ylabel('Average District Score (SAT Math)')
plt.ylim(0, 600)
plt.show()

X = np.array(df['After_School_Supper_ADP']).reshape(-1, 1)
y = np.array(df['Average District Score (SAT Reading)']).reshape(-1, 1)
lm.fit(X, y)

plt.scatter(df['After_School_Supper_ADP'], df['Average District Score (SAT Reading)'])
plt.plot(X, lm.predict(X))
plt.xlabel('After School Supper ADP')
plt.ylabel('Average District Score (SAT Reading)')
plt.ylim(0, 600)
plt.show()

X = np.array(df['After_School_Supper_ADP']).reshape(-1, 1)
y = np.array(df['Average District Score (SAT Writing)']).reshape(-1, 1)
lm.fit(X, y)

plt.scatter(df['After_School_Supper_ADP'], df['Average District Score (SAT Writing)'])
plt.plot(X, lm.predict(X))
plt.xlabel('After School Supper ADP')
plt.ylabel('Average District Score (SAT Writing)')
plt.ylim(0, 600)
plt.show()

X = np.array(df['Lunch_ADP']).reshape(-1, 1)
y = np.array(df['Average District Score (SAT Math)']).reshape(-1, 1)
lm.fit(X, y)

plt.scatter(df['Lunch_ADP'], df['Average District Score (SAT Math)'])
plt.plot(X, lm.predict(X))
plt.xlabel('Lunch ADP')
plt.ylabel('Average District Score (SAT Math)')
plt.ylim(0, 600)
plt.show()

X = np.array(df['Lunch_ADP']).reshape(-1, 1)
y = np.array(df['Average District Score (SAT Reading)']).reshape(-1, 1)
lm.fit(X, y)

plt.scatter(df['Lunch_ADP'], df['Average District Score (SAT Reading)'])
plt.plot(X, lm.predict(X))
plt.xlabel('Lunch ADP')
plt.ylabel('Average District Score (SAT Reading)')
plt.ylim(0, 600)
plt.show()

X = np.array(df['Lunch_ADP']).reshape(-1, 1)
y = np.array(df['Average District Score (SAT Writing)']).reshape(-1, 1)
lm.fit(X, y)

plt.scatter(df['Lunch_ADP'], df['Average District Score (SAT Writing)'])
plt.plot(X, lm.predict(X))
plt.xlabel('Lunch ADP')
plt.ylabel('Average District Score (SAT Writing)')
plt.ylim(0, 600)
plt.show()

X = np.array(df['Breakfast_ADP']).reshape(-1, 1)
y = np.array(df['Average District Score (SAT Math)']).reshape(-1, 1)
lm.fit(X, y)

plt.scatter(df['Breakfast_ADP'], df['Average District Score (SAT Math)'])
plt.plot(X, lm.predict(X))
plt.xlabel('Breakfast ADP')
plt.ylabel('Average District Score (SAT Math)')
plt.ylim(0, 600)
plt.show()

X = np.array(df['Breakfast_ADP']).reshape(-1, 1)
y = np.array(df['Average District Score (SAT Reading)']).reshape(-1, 1)
lm.fit(X, y)

plt.scatter(df['Breakfast_ADP'], df['Average District Score (SAT Reading)'])
plt.plot(X, lm.predict(X))
plt.xlabel('Breakfast ADP')
plt.ylabel('Average District Score (SAT Reading)')
plt.ylim(0, 600)
plt.show()

X = np.array(df['Breakfast_ADP']).reshape(-1, 1)
y = np.array(df['Average District Score (SAT Writing)']).reshape(-1, 1)
lm.fit(X, y)

plt.scatter(df['Breakfast_ADP'], df['Average District Score (SAT Writing)'])
plt.plot(X, lm.predict(X))
plt.xlabel('Breakfast ADP')
plt.ylabel('Average District Score (SAT Writing)')
plt.ylim(0, 600)
plt.show()